# generated by huangwf @ 2021.02.07

cc_binary (
    name = 'test_uniq_id',
    srcs = [
        'demo/test_uniq_id.cpp',
    ],
    deps = [
        ':cpp_common',
    ],
    extra_linkflags = [
        '-pthread',
    ],
)

cc_library (
    visibility = ['PUBLIC'],
    name = 'cpp_common',
    srcs = [
        'uniq_id/snow_flake.cpp',
        'utils/facility.cpp',
    ],
    hdrs = [
        'uniq_id/snow_flake.h',
        'utils/facility.h',
    ],
    extra_linkflags = [
        '-pthread'
    ],
)
