# generated by huangwf @ 2021.02.07

cc_library (
    visibility = ['PUBLIC'],
    name = 'cpp_common',
    srcs = [
        'uniq_id/snow_flake.cpp',
        'utils/facility.cpp',
    ],
    hdrs = [
        'uniq_id/snow_flake.hpp',
        'utils/facility.hpp',
    ],
    extra_linkflags = [
        '-pthread'
    ],
)
